baseURL = "https://web-pruebas.vercel.app/blog/"
relativeURLs = false
canonifyURLs = true
DefaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
languageCode = "es-uy"
title = "Electricidad para todos"
theme = "lightbi-hugo"
metaDataFormat = "toml"
pygmentsStyle = "trac"
pygmentsCodefencesGuessSyntax = true
enableRobotsTXT = true
enableGitInfo = false
summaryLength = "10"
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
  pagerSize = 6

[Params]
  # Información del sitio y SEO
  author = "Tu Nombre"
  description = "Blog especializado en electricidad domiciliaria en Maldonado y Punta del Este, Uruguay"
  logo = "images/logo.png"
  
  # SEO específico para electricidad
  keywords = ["electricidad", "electricista", "Maldonado", "Punta del Este", "Uruguay", "instalaciones eléctricas", "seguridad eléctrica"]
  
  # Configuraciones del tema lightbi-hugo
  selfHosted = true
  mainSections = ["post","posts"]
  dateFormat = "02 January 2006"
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  summaryLength = "70"
  lunrSearch = true
  gcse = false
  lastmod = false
  rss = false
  pagination = "10"
  hideAuthor = false
  previewCardImagePlacement = "bottom"
  showPostImage = false
  
  # Integraciones de negocio eléctrico
  googleBusinessURL = "https://g.page/tu-negocio"
  
  # Servidor de imágenes
  imageServer = "https://ik.imagekit.io/tnzquipyu/tr:w-xxx,h-auto/"
  
  # Banner tipo marquesina (deshabilitado por defecto)
  enableMarqueeBanner = false
  marqueeBannerText = "Servicio de emergencia 24/7 - Llámanos al +598 XXXXXXXX"
  
  # Tarjeta pop-up para promocionar servicios eléctricos
  enablePopupCard = false
  popupCardDelay = 5
  popupCardDuration = 30
  popupCardTitle = "¿Necesitas un electricista?"
  popupCardContent = "Visita nuestra página de contacto para servicios profesionales de electricidad"
  popupCardButtonText = "Contactar ahora"
  popupCardButtonURL = "/contact/"

[Params.Author]
  name = "Jorge Electricidad"
  website = "https://www.tudominio.com/"
  authorInfo = "Electricista profesional en Maldonado y Punta del Este con más de X años de experiencia"
  authorPostImage = "/img/author-post-img.jpg"
  email = "jorgitobaliero@gmail.com"
  phone = "+598 93601446"
  address = "Maldonado, Uruguay"
  
  # Redes sociales
 # facebook = "username"
  #instagram = "username"
  #youtube = "user/username" 
  #twitter = "jtorres"
  linkedin = "j-e-torres"
 # github = "username"
  #telegram = "username"
  
[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 2

#[[menu.main]]
#    name = "Notas"
#    url = "/notes/"
#    weight = 3

#[[menu.main]]
#    name = "Etiquetas"
#    url = "/tags/"
#    weight = 4

#[[menu.main]]
#    name = "Acerca de"
#    url = "/about/"
#    weight = 5

#[[menu.main]]
#    name = "Contacto"
#    url = "/contact/"
#    weight = 6

# Taxonomías
[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"